// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface Model {
	id: string;
	created_at: string /* RFC3339 */;
	updated_at: string /* RFC3339 */;
	deleted_at: string | null;
}
export interface File {
	Model: Model;
	Type: string;
}
export interface InviteLink extends Model {
	server_id: string;
	joins_left: number /* uint */;
}
export interface Server {
	Model: Model;
	name: string;
	owner_id: string;
	avatar: string;
	channels?: Channel[];
}
export interface Channel {
	Model: Model;
	server_id: string;
	name: string;
	type: string;
}
export interface Membership {
	Model: Model;
	user_id: string;
	server_id: string;
	banned: boolean;
}
export interface Role extends Model {
	server_id: string;
	name: string;
	color: string;
	permissions: string[];
}
export interface UserRole {
	Model: Model;
	user_id: string;
	role_id: string;
	server_id: string;
}
export interface ChannelPermissionOverride {
	Model: Model;
	server_id: string;
	channel_id: string;
	role_id: string;
	allow_mask: string[];
	deny_mask: string[];
}
export interface User {
	Model: Model;
	name: string;
	avatar: string;
}
export interface UserResponse {
	id: string;
	name: string;
	avatar: string;
}
export interface ChannelResponse {
	id: string;
	name: string;
	server_id: string;
	type: string;
}
export interface Message {
	Model: Model;
	content: string;
	user_id: string;
	channel_id: string;
	user: User;
}
export interface MessageResponse {
	id: string;
	content: string;
	user_id: string;
	user: User;
	channel_id: string;
	created_at: string /* RFC3339 */;
}
export interface MembershipResponse {
	id: string;
	user_id: string;
	server_id: string;
	role: string;
}
export interface ServerResponse {
	id: string;
	name: string;
	owner_id: string;
	avatar: string;
	channels: ChannelResponse[];
}
export interface MessageHistoryResponse {
	id: string;
	content: string;
	user_id: string;
	created_at: string /* RFC3339 */;
	updated_at: string /* RFC3339 */;
}
export interface ChannelHistoryResponse {
	messages: MessageHistoryResponse[];
	users: UserResponse[];
}
