//	@title			Solace API
//	@version		1.0
//	@description	a messaging app api
//	@host			localhost:1323
//	@BasePath		/api

package server

import (
	"solace/middleware"

	"github.com/labstack/echo/v4"
	echoMiddleware "github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
	"gorm.io/gorm"

	_ "solace/docs" // docs is generated by Swag CLI, you have to import it.
)

type Server struct {
	echo      *echo.Echo
	db        *gorm.DB
	SecretKey []byte
}

func NewServer(db *gorm.DB, secretKey []byte) *Server {
	return &Server{
		echo:      echo.New(),
		db:        db,
		SecretKey: secretKey,
	}
}

func (s *Server) Start(addr string) error {
	s.registerRoutes()
	return s.echo.Start(addr)
}

func (s *Server) registerRoutes() {
	// global middleware
	s.echo.Use(echoMiddleware.CORSWithConfig(echoMiddleware.CORSConfig{
		AllowOrigins:     []string{"https://*", "http://*"},
		AllowMethods:     []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowHeaders:     []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
		AllowCredentials: true,
		MaxAge:           300,
	}))
	s.echo.Use(echoMiddleware.RequestLogger())
	s.echo.Use(middleware.JWTMiddleware(s.db, s.SecretKey))
	s.echo.GET("/swagger/*", echoSwagger.WrapHandler)

	// main group
	g := s.echo.Group("/api")

	// auth routes
	g.POST("/auth/login", s.Login)
	g.POST("/auth/register", s.Register)
	g.GET("/auth/refresh", s.Refresh, middleware.RequireAuth())

	// user routes
	userGroup := g.Group("/user")
	userGroup.Use(middleware.RequireAuth())
	userGroup.GET("/me", s.UserGet)

	// server routes
	serverGroup := g.Group("/server")
	serverGroup.Use(middleware.RequireAuth())
	serverGroup.GET("/:id", s.ServerGet)
	serverGroup.POST("", s.ServerNew)
	serverGroup.POST("/:id/new_channel", s.ChannelNew)
	// serverGroup.POST("/:id/avatar", s.SetServerAvatar)
	serverGroup.POST("/:id/kick", s.ServerKick)
	serverGroup.POST("/:id/links", s.LinksNew)
	serverGroup.GET("/:id/links", s.LinksList)
	serverGroup.DELETE("/:id/links/:invite_id", s.LinksRevoke)
	serverGroup.POST("/join/:invite_id", s.LinksJoin)

	// roles
	serverGroup.POST("/:id/roles", s.RoleCreate)
	serverGroup.GET("/:id/roles", s.RoleList)
	serverGroup.GET("/:id/user/roles", s.UserRoles)
	serverGroup.PUT("/:id/roles/:role_id", s.RoleUpdate)
	serverGroup.DELETE("/:id/roles/:role_id", s.RoleDelete)
	serverGroup.PUT("/:id/roles/assign/:user_id/:role_id", s.RoleAssign)

	// member actions
	// serverGroup.PUT("/:id/members/:member_id/ban", s.ServerBan)
	// serverGroup.PUT("/;id/members/:member_id/assign", s.RoleAssign)

	// channel routes
	channelGroup := g.Group("/channel")
	channelGroup.Use(middleware.RequireAuth())
	channelGroup.POST("/:id/send", s.MessageSend)
	channelGroup.POST("/:id/history", s.ChannelHistory)
	channelGroup.DELETE("/:id", s.ChannelDelete)

	// message routes
	messageGroup := g.Group("/message")
	messageGroup.Use(middleware.RequireAuth())
	messageGroup.DELETE("/:id", s.MessageDelete)
	messageGroup.PATCH("/:id", s.MessageEdit)

	// sse routes
	websocketGroup := s.echo.Group("/api/ws")
	websocketGroup.GET("/connect", s.WSConnect)

	// file routes
	fileGroup := s.echo.Group("/api/file")
	fileGroup.Use(middleware.RequireAuth())
	fileGroup.GET("/:id", s.FileGet)
	fileGroup.POST("/upload", s.FilePost)
}
